---
layout: post
title: "Copenhagen Agenda"
---

# Agenda

DINA Technical workshop 2-6 Nov 2015 Copenhagen

The workshop will be held in the Zoological Museum, Universitetsparken 15 in the meeting room.

The meeting will start with the lunch at 12:00 on Monday, which will be held in August Krogh Institute (Universitetsparken 13, next door to the musem). If you're early and/or want to drop of suitcases etc, go to the Museum main entry. The museum does not have a reception, but the staff in the museum shop will be informed about the meeting and can show you the way to the meeting room. If anything goes wrong you can call Martin Stein on +45 222 559 00.

# Monday 12.00-16.30

    12.00-13.00 Lunch 

Overview - progress reports from all parties:

    13.00-13.30 - Welcome! DINA introduction (Fredrik Ronquist)
    13.30-14.00 - DK (Nikolaj Scharff/Thomas Stjernegaard Jeppesen)
    14.00-14.30 - EE (Urmas Kõljag)
    14.30-15.00 Coffee break
    15.00-15.30 - DE (Falko Glöckler)
    15.30-16.00 - CA (James Macklin)
    16.00-16.30 - SE (Markus Skyttner) 

# Tuesday 09.00-16.30

DINA Road Map

    09.00-12.00 Discussion: Module map, API blueprints, Milestones/Feature sets
    12.00-13.00 Lunch
    13.00-16.30 Continuing discussion/breakout sessions: Module map, API blueprints, Milestones/Feature sets 

# Wednesday 09.00-11.00

Conclusion: DINA Road map

    Wednesday 9.00-10.00 Conclusion: DINA Road map (Fredrik Ronquist) 

Presentation GBIF

    Wednesday 10.00-11.00 Presentation GBIF (Tim Robertson) 

# Wednesday 11.00-16.30 - hackathons/coding sessions

DINA APIs

    APIs discussion - comparison of APIs visavi Pluto-F, Specify 7 and identifying overlaps/unique differentiators and formulating DINA-Specify specific needs.
    Hackathon: API blueprints: “Apiary” (Markus Skyttner) 

User module

    User module/user rights/Specify resource management for the DINA-Web collection manager (Markus Skyttner and Ida Li)
    Hackathon: get the bare bones metal DINA-Web box up and running (Markus Skyttner) 

# Thursday 09.00-16.30 - hackathons/coding sessions

DINA Data Tool

    Hackathon: Integration of DDT – vagrant file using Bitnami node JS stack (Markus Skyttner and Thomas Stjernegaard Jeppesen)
    Support installation of the DINA Data Tool on other partners' servers (Thomas Stjernegaard Jeppesen) 

Accessibility and Security

    Accessibility tools and guidelines/Security tools overview and guidelines – (Glen Newton)
    Run security tools on the existing web applications (Glen Newton)
    Run accessibility tools on the existing web applications (Glen Newton)
    Hackathon - security review of DINA packaging at system level (Glen Newton) 

DNA module

    SeqDB – voucher data, integration with DINA collection manager (Satpal Bilkhu)
    SeqDB web service examples (Satpal Bilkhu) 

Friday 09.00-12.00

    09.00-12.00 Concluding discussion - next steps
    12.00-13.00 Lunch - Meeting ends 
